version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    container_name: front
    build:
      context: ./frontend/bookwise-front
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - backend